version: '3.7'

services:

  # Traefik Reverse Proxy
  traefik:
    image: traefik:alpine
    container_name: traefik
    domainname: ${DOMAINNAME}
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/traefik:/etc/traefik
      - ${USERDIR}/shared:/shared

  # Database for HA
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ${USERDIR}/postgres:/var/lib/postgresql/data
      - ${USERDIR}/shared:/shared
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      TZ: ${TZ}


  # MQTT broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: always
    volumes:
      - ${USERDIR}/mosquitto/data:/mosquitto/data
      - ${USERDIR}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${USERDIR}/mosquitto/log:/mosquitto/log
      - ${USERDIR}/shared:/shared
    environment:
      TZ: ${TZ}


  # Home Assistant
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - ${USERDIR}/home-assistant:/config
      - ${USERDIR}/shared:/shared
    environment:
      TZ: ${TZ}
      HOSTIP: ${HOSTIP}

  appdaemon:
    container_name: homeassistant_appdaemon
    image: acockburn/appdaemon:latest
    depends_on:
      # Start home-assistant first
      - homeassistant
    links:
      # Link ports from home-assistant container
      - homeassistant
    ports:
      - 5050:5050
    volumes:
      # App daemon configuration
      - ${USERDIR}/appdaemon:/conf
      # Timezone configuration (Linux only)
      - /etc/localtime:/etc/localtime:ro
    restart: always


  # InfluxDB
  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ${USERDIR}/influxdb:/var/lib/influxdb
      - ${USERDIR}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${USERDIR}/shared:/shared
    environment:
      INFLUXDB_DB: ${DBNAME}
      INFLUXDB_USER: ${DBUSER}
      INFLUXDB_USER_PASSWORD: ${DBPASS}
      TZ: ${TZ}

# Networks that are needed
networks:
  traefik_proxy:
    name: traefik_proxy
  default:
    driver: bridge
